import QuartetDistance.Circular

/-!
# Circular orders modulo dihedral reindexing

`Circular.CircularOrder n` is deliberately a linear representative.  Here we
form the actual quotient generated by the one-step cyclic shift of positions
and reversal of positions.  The crossing split on every label quartet, and
hence the paper's statistic `K`, descend to this quotient.
-/

namespace QuartetDistance.CircularQuotient

open scoped BigOperators

open Circular

/-! ## A list description of the crossing split -/

/-- Restrict a word to the labels in `Q`. -/
def restrictLabels [DecidableEq X] (Q : Finset X) (l : List X) : List X :=
  l.filter fun x => x ∈ Q

/-- Opposite terms in a four-term word determine its crossing split. -/
def crossingList [DecidableEq X] : List X → QuartetSplit X
  | [a, b, c, d] => splitOf a b c d
  | _ => ∅

theorem splitOf_rotate [DecidableEq X] (a b c d : X) :
    splitOf a b c d = splitOf b c d a := by
  ext A
  simp [splitOf, pair]
  aesop

theorem splitOf_reverse [DecidableEq X] (a b c d : X) :
    splitOf a b c d = splitOf d c b a := by
  ext A
  simp [splitOf, pair]
  aesop

theorem crossingList_cons_eq_append_singleton [DecidableEq X]
    (a : X) (zs : List X) (hz : zs.length = 3) :
    crossingList (a :: zs) = crossingList (zs ++ [a]) := by
  obtain ⟨b, c, d, rfl⟩ := List.length_eq_three.mp hz
  exact splitOf_rotate _ _ _ _

theorem crossingList_reverse [DecidableEq X] (l : List X)
    (hl : l.length = 4) :
    crossingList l.reverse = crossingList l := by
  obtain ⟨a, b, c, d, rfl⟩ := List.length_eq_four.mp hl
  exact (splitOf_reverse _ _ _ _).symm

theorem crossingList_filter_rotate_one [DecidableEq X]
    (Q : Finset X) (l : List X)
    (hl : (restrictLabels Q l).length = 4) :
    crossingList (restrictLabels Q (l.rotate 1)) =
      crossingList (restrictLabels Q l) := by
  cases l with
  | nil => simp [restrictLabels] at hl
  | cons a l =>
      simp only [List.rotate_cons_succ, List.rotate_zero]
      by_cases ha : a ∈ Q
      · have htail : (restrictLabels Q l).length = 3 := by
          simpa [restrictLabels, ha] using hl
        simpa [restrictLabels, ha, List.filter_append] using
          (crossingList_cons_eq_append_singleton a (restrictLabels Q l) htail).symm
      · simp [restrictLabels, ha, List.filter_append]

theorem crossingList_filter_reverse [DecidableEq X]
    (Q : Finset X) (l : List X)
    (hl : (restrictLabels Q l).length = 4) :
    crossingList (restrictLabels Q l.reverse) =
      crossingList (restrictLabels Q l) := by
  rw [restrictLabels, List.filter_reverse]
  exact crossingList_reverse _ hl

/-! ## Representatives and their underlying words -/

theorem circularOrderList_rotate (C : Circular.CircularOrder n) :
    circularOrderList ((finRotate n).trans C) =
      (circularOrderList C).rotate 1 := by
  cases n with
  | zero => simp [circularOrderList]
  | succ n =>
      unfold circularOrderList
      change List.ofFn (fun i => C (finRotate (n + 1) i)) =
        (List.ofFn C).rotate 1
      rw [List.ofFn_succ' (fun i => C (finRotate (n + 1) i))]
      rw [List.ofFn_succ (f := C)]
      simp only [List.rotate_cons_succ, List.rotate_zero]
      rw [finRotate_last]
      rw [List.concat_eq_append]
      congr 1
      apply congrArg List.ofFn
      funext i
      apply C.injective
      apply Fin.ext
      simp [finRotate_apply]

theorem ofFn_rev : ∀ (n : ℕ) (f : Fin n → X),
    List.ofFn (fun i => f i.rev) = (List.ofFn f).reverse
  | 0, f => by simp
  | n + 1, f => by
      rw [List.ofFn_succ, List.ofFn_succ', List.concat_eq_append,
        List.reverse_concat]
      rw [Fin.rev_zero]
      congr 1
      simpa only [Fin.rev_succ] using
        ofFn_rev n (fun i : Fin n => f i.castSucc)

theorem circularOrderList_reverse (C : Circular.CircularOrder n) :
    circularOrderList (Fin.revPerm.trans C) =
      (circularOrderList C).reverse := by
  exact ofFn_rev n C

/-! ### Bridge to `Circular.crossingOnLabels` -/

theorem finRange_filter_mem_eq_sort (s : Finset (Fin n)) :
    (List.finRange n).filter (fun i => i ∈ s) = s.sort (· ≤ ·) := by
  have hp :
      List.Perm ((List.finRange n).filter (fun i => i ∈ s)) (s.sort (· ≤ ·)) := by
    apply (List.perm_ext_iff_of_nodup
      ((List.nodup_finRange n).filter _) (Finset.sort_nodup s _)).2
    intro i
    simp
  have hslt : List.Pairwise (· < ·)
      ((List.finRange n).filter (fun i => i ∈ s)) :=
    (List.sortedLT_finRange n).pairwise.filter _
  have hsle : List.Pairwise (· ≤ ·)
      ((List.finRange n).filter (fun i => i ∈ s)) :=
    hslt.imp fun h => le_of_lt h
  exact hp.eq_of_sortedLE hsle.sortedLE (s.sortedLT_sort.sortedLE)

theorem ofFn_enumerateFour_eq_sort (s : Finset (Fin n)) (h : s.card = 4) :
    List.ofFn (enumerateFour s h) = s.sort (· ≤ ·) := by
  have hlength : (s.sort (· ≤ ·)).length = 4 := by simp [h]
  calc
    List.ofFn (enumerateFour s h) =
        List.ofFn (fun i : Fin 4 =>
          (s.sort (· ≤ ·)).get (Fin.cast hlength.symm i)) := by
      apply congrArg List.ofFn
      funext i
      simp [enumerateFour, Finset.orderEmbOfFin_apply]
    _ = List.ofFn (s.sort (· ≤ ·)).get :=
      (List.ofFn_congr hlength (s.sort (· ≤ ·)).get).symm
    _ = s.sort (· ≤ ·) := List.ofFn_get _

theorem restrict_circularOrderList_eq_ofFn_crossingEmbedding
    (C : Circular.CircularOrder n) (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    restrictLabels Q (circularOrderList C) =
      List.ofFn
        ((enumerateFour (labelPositions C Q)
          (by simpa using hQ)).trans C.toEmbedding) := by
  let p := labelPositions C Q
  have hp : p.card = 4 := by simpa [p] using hQ
  have hpred :
      (fun i : Fin n => decide (C i ∈ Q)) =
        (fun i : Fin n => decide (i ∈ p)) := by
    funext i
    simp [p, labelPositions]
  unfold restrictLabels circularOrderList
  rw [List.ofFn_eq_map, List.filter_map]
  change List.map C ((List.finRange n).filter fun i => C i ∈ Q) = _
  rw [hpred, finRange_filter_mem_eq_sort]
  rw [← ofFn_enumerateFour_eq_sort p hp]
  exact List.ofFn_comp' _ _ |>.symm

@[simp] theorem crossingList_of_embedding [DecidableEq X] (q : Four ↪ X) :
    crossingList [q 0, q 1, q 2, q 3] = crossing q := by
  simp [crossingList, crossing, canonicalCrossing, mapSplit, splitOf, pair]

theorem crossingOnLabels_eq_crossingList_restrict_circularOrderList
    (C : Circular.CircularOrder n) (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    crossingOnLabels C Q hQ =
      crossingList (restrictLabels Q (circularOrderList C)) := by
  rw [restrict_circularOrderList_eq_ofFn_crossingEmbedding C Q hQ]
  let r : Four ↪ Fin n :=
    (enumerateFour (labelPositions C Q)
      (by simpa using hQ)).trans C.toEmbedding
  change crossing r = crossingList [r 0, r 1, r 2, r 3]
  exact (crossingList_of_embedding r).symm

theorem restrictLabels_circularOrderList_length
    (C : Circular.CircularOrder n) (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    (restrictLabels Q (circularOrderList C)).length = 4 := by
  rw [restrict_circularOrderList_eq_ofFn_crossingEmbedding C Q hQ]
  simp

theorem crossingOnLabels_rotate (C : Circular.CircularOrder n)
    (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    crossingOnLabels ((finRotate n).trans C) Q hQ =
      crossingOnLabels C Q hQ := by
  rw [crossingOnLabels_eq_crossingList_restrict_circularOrderList,
    crossingOnLabels_eq_crossingList_restrict_circularOrderList,
    circularOrderList_rotate]
  exact crossingList_filter_rotate_one Q (circularOrderList C)
    (restrictLabels_circularOrderList_length C Q hQ)

theorem crossingOnLabels_reverse (C : Circular.CircularOrder n)
    (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    crossingOnLabels (Fin.revPerm.trans C) Q hQ =
      crossingOnLabels C Q hQ := by
  rw [crossingOnLabels_eq_crossingList_restrict_circularOrderList,
    crossingOnLabels_eq_crossingList_restrict_circularOrderList,
    circularOrderList_reverse]
  exact crossingList_filter_reverse Q (circularOrderList C)
    (restrictLabels_circularOrderList_length C Q hQ)

/-! ## The generated dihedral quotient -/

/-- An elementary change of representative: rotate the position word once,
or reverse it. -/
def ReindexStep (C C' : Circular.CircularOrder n) : Prop :=
  C' = (finRotate n).trans C ∨ C' = Fin.revPerm.trans C

/-- The equivalence relation generated by the elementary rotation and
reversal steps.  Repeating the rotation gives every cyclic shift, and
composing with reversal gives every dihedral reindexing. -/
abbrev ReindexRelated (C C' : Circular.CircularOrder n) : Prop :=
  Relation.EqvGen (@ReindexStep n) C C'

/-- The setoid of representative words modulo cyclic shifts and reversal. -/
def circularOrderSetoid (n : ℕ) : Setoid (Circular.CircularOrder n) :=
  Relation.EqvGen.setoid (@ReindexStep n)

/-- A genuine circular order: a permutation word modulo cyclic shifts and
reversal. -/
def DihedralCircularOrder (n : ℕ) : Type :=
  Quotient (circularOrderSetoid n)

/-- Send a linear representative to its circular-order class. -/
def mk (C : Circular.CircularOrder n) : DihedralCircularOrder n :=
  Quotient.mk (circularOrderSetoid n) C

theorem mk_eq_mk_of_related {C C' : Circular.CircularOrder n}
    (h : ReindexRelated C C') : mk C = mk C' :=
  Quotient.sound (s := circularOrderSetoid n) h

theorem mk_eq_mk_iff {C C' : Circular.CircularOrder n} :
    mk C = mk C' ↔ ReindexRelated C C' := by
  constructor
  · exact fun h => Quotient.exact h
  · exact mk_eq_mk_of_related

@[simp] theorem mk_rotate (C : Circular.CircularOrder n) :
    mk ((finRotate n).trans C) = mk C := by
  apply Quotient.sound
  exact Relation.EqvGen.symm _ _
    (Relation.EqvGen.rel _ _ (Or.inl rfl : ReindexStep C ((finRotate n).trans C)))

@[simp] theorem mk_reverse (C : Circular.CircularOrder n) :
    mk (Fin.revPerm.trans C) = mk C := by
  apply Quotient.sound
  exact Relation.EqvGen.symm _ _
    (Relation.EqvGen.rel _ _ (Or.inr rfl : ReindexStep C (Fin.revPerm.trans C)))

/-- Pointwise crossing splits are constant on the generated equivalence
classes of representatives. -/
theorem crossingOnLabels_eq_of_related
    {C C' : Circular.CircularOrder n} (h : ReindexRelated C C')
    (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    crossingOnLabels C Q hQ = crossingOnLabels C' Q hQ := by
  induction h with
  | rel C C' hstep =>
      rcases hstep with hrot | hrev
      · subst C'
        exact (crossingOnLabels_rotate C Q hQ).symm
      · subst C'
        exact (crossingOnLabels_reverse C Q hQ).symm
  | refl C => rfl
  | symm C C' _ ih => exact ih.symm
  | trans C C' C'' _ _ ih ih' => exact ih.trans ih'

/-! ## Crossing splits on quotient circular orders -/

/-- The crossing split selected by a quotient circular order on a fixed
four-element label set. -/
noncomputable def quotientCrossing (O : DihedralCircularOrder n)
    (Q : Finset (Fin n)) (hQ : Q.card = 4) : QuartetSplit (Fin n) :=
  Quotient.lift (fun C => crossingOnLabels C Q hQ)
    (fun _ _ h => crossingOnLabels_eq_of_related h Q hQ) O

@[simp] theorem quotientCrossing_mk (C : Circular.CircularOrder n)
    (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    quotientCrossing (mk C) Q hQ = crossingOnLabels C Q hQ := by
  rfl

theorem crossingOnLabels_isQuartetSplit (C : Circular.CircularOrder n)
    (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    IsQuartetSplit Q (crossingOnLabels C Q hQ) := by
  let p := labelPositions C Q
  let hp : p.card = 4 := by simpa [p] using hQ
  let r : Four ↪ Fin n := (enumerateFour p hp).trans C.toEmbedding
  have hrange : Finset.univ.map r = Q := by
    calc
      Finset.univ.map r =
          (Finset.univ.map (enumerateFour p hp)).map C.toEmbedding := by
            exact (Finset.map_map _ _ _).symm
      _ = p.map C.toEmbedding := by rw [range_enumerateFour]
      _ = Q := by
        ext x
        simp [p, labelPositions]
  exact ⟨r, hrange.symm, rfl⟩

/-- Every quotient circular order selects a well-formed split on every
four-subset. -/
theorem quotientCrossing_isQuartetSplit (O : DihedralCircularOrder n)
    (Q : Finset (Fin n)) (hQ : Q.card = 4) :
    IsQuartetSplit Q (quotientCrossing O Q hQ) := by
  induction O using Quotient.inductionOn with
  | _ C => exact crossingOnLabels_isQuartetSplit C Q hQ

/-! ## The statistic `K` on quotient circular orders -/

/-- Two quotient circular orders agree on the crossing split of `Q`. -/
def CrossingAgrees (O O' : DihedralCircularOrder n)
    (Q : Finset (Fin n)) : Prop :=
  ∃ hQ : Q.card = 4, quotientCrossing O Q hQ = quotientCrossing O' Q hQ

noncomputable instance (O O' : DihedralCircularOrder n)
    (Q : Finset (Fin n)) : Decidable (CrossingAgrees O O' Q) :=
  Classical.dec _

/-- The number of label quartets on which two quotient circular orders select
the same crossing split. -/
noncomputable def K (O O' : DihedralCircularOrder n) : ℕ :=
  ((Finset.univ.powersetCard 4).filter (CrossingAgrees O O')).card

/-- On representatives, quotient `K` is the label-set count from
`Circular`. -/
theorem K_mk_mk_eq_labelK (C C' : Circular.CircularOrder n) :
    K (mk C) (mk C') = labelK C C' := by
  classical
  unfold K labelK
  congr 1

/-- Thus quotient `K` is exactly the existing representative statistic. -/
@[simp] theorem K_mk_mk (C C' : Circular.CircularOrder n) :
    K (mk C) (mk C') = Circular.K C C' := by
  rw [K_mk_mk_eq_labelK, labelK_eq_K]

theorem K_le_choose (O O' : DihedralCircularOrder n) :
    K O O' ≤ Nat.choose n 4 := by
  induction O using Quotient.inductionOn with
  | _ C =>
      induction O' using Quotient.inductionOn with
      | _ C' =>
          change K (mk C) (mk C') ≤ Nat.choose n 4
          rw [K_mk_mk]
          exact Circular.K_le_choose C C'

theorem K_comm (O O' : DihedralCircularOrder n) : K O O' = K O' O := by
  induction O using Quotient.inductionOn with
  | _ C =>
      induction O' using Quotient.inductionOn with
      | _ C' =>
          change K (mk C) (mk C') = K (mk C') (mk C)
          rw [K_mk_mk, K_mk_mk]
          exact Circular.K_comm C C'

theorem K_self (O : DihedralCircularOrder n) : K O O = Nat.choose n 4 := by
  induction O using Quotient.inductionOn with
  | _ C =>
      change K (mk C) (mk C) = Nat.choose n 4
      rw [K_mk_mk]
      exact Circular.K_self C

/-- The paper's finite circular-order lower bound stated directly on genuine
circular orders modulo cyclic shift and reversal, rather than on chosen
linear representatives. -/
theorem circularOrderBound (hpublished : Circular.StepPermutonTheorem n)
    (O O' : DihedralCircularOrder n) (hn : 4 ≤ n) :
    (1 - 2 / (3 * Circular.stepAlpha n)) * (Nat.choose n 4 : ℚ) ≤ K O O' := by
  induction O using Quotient.inductionOn with
  | _ C =>
      induction O' using Quotient.inductionOn with
      | _ C' =>
          change (1 - 2 / (3 * Circular.stepAlpha n)) *
              (Nat.choose n 4 : ℚ) ≤ (K (mk C) (mk C') : ℚ)
          rw [K_mk_mk]
          exact Circular.circularOrderBound hpublished C C' hn

/-! Explicit representative-invariance corollaries. -/

theorem representative_K_rotate_left (C C' : Circular.CircularOrder n) :
    Circular.K ((finRotate n).trans C) C' = Circular.K C C' := by
  calc
    Circular.K ((finRotate n).trans C) C' =
        K (mk ((finRotate n).trans C)) (mk C') :=
      (K_mk_mk _ _).symm
    _ = K (mk C) (mk C') := by rw [mk_rotate]
    _ = Circular.K C C' := K_mk_mk _ _

theorem representative_K_reverse_left (C C' : Circular.CircularOrder n) :
    Circular.K (Fin.revPerm.trans C) C' = Circular.K C C' := by
  calc
    Circular.K (Fin.revPerm.trans C) C' =
        K (mk (Fin.revPerm.trans C)) (mk C') :=
      (K_mk_mk _ _).symm
    _ = K (mk C) (mk C') := by rw [mk_reverse]
    _ = Circular.K C C' := K_mk_mk _ _

theorem representative_K_rotate_right (C C' : Circular.CircularOrder n) :
    Circular.K C ((finRotate n).trans C') = Circular.K C C' := by
  rw [Circular.K_comm, representative_K_rotate_left, Circular.K_comm]

theorem representative_K_reverse_right (C C' : Circular.CircularOrder n) :
    Circular.K C (Fin.revPerm.trans C') = Circular.K C C' := by
  rw [Circular.K_comm, representative_K_reverse_left, Circular.K_comm]

/-- `Circular.K` is invariant under an arbitrary generated change of its
first representative, not merely under one generator step. -/
theorem representative_K_eq_of_related_left
    {C D : Circular.CircularOrder n} (h : ReindexRelated C D)
    (C' : Circular.CircularOrder n) : Circular.K C C' = Circular.K D C' := by
  calc
    Circular.K C C' = K (mk C) (mk C') := (K_mk_mk _ _).symm
    _ = K (mk D) (mk C') := by rw [mk_eq_mk_of_related h]
    _ = Circular.K D C' := K_mk_mk _ _

/-- `Circular.K` is invariant under an arbitrary generated change of its
second representative. -/
theorem representative_K_eq_of_related_right
    (C : Circular.CircularOrder n) {C' D' : Circular.CircularOrder n}
    (h : ReindexRelated C' D') : Circular.K C C' = Circular.K C D' := by
  calc
    Circular.K C C' = K (mk C) (mk C') := (K_mk_mk _ _).symm
    _ = K (mk C) (mk D') := by rw [mk_eq_mk_of_related h]
    _ = Circular.K C D' := K_mk_mk _ _

theorem representative_K_congr
    {C D C' D' : Circular.CircularOrder n}
    (h : ReindexRelated C D) (h' : ReindexRelated C' D') :
    Circular.K C C' = Circular.K D D' := by
  rw [representative_K_eq_of_related_left h,
    representative_K_eq_of_related_right D h']

end QuartetDistance.CircularQuotient
