import QuartetDistance.Circular

/-!
# The eight patterns as a generated dihedral subgroup

The paper describes its eight distinguished permutations both by listing
them and as the subgroup generated by the four-cycle `2341` and the
reflection `4321`.  `Circular` uses the explicit list in the counting proof;
this file proves that the two descriptions coincide.
-/

namespace QuartetDistance.Circular

/-- The explicit eight-pattern predicate is closed under the group
operations. -/
def dihedralSubgroup : Subgroup Perm4 where
  carrier := (dihedral4 : Set Perm4)
  one_mem' := by decide
  mul_mem' := by decide
  inv_mem' := by decide

@[simp] theorem mem_dihedralSubgroup (σ : Perm4) :
    σ ∈ dihedralSubgroup ↔ IsDihedral4 σ :=
  (isDihedral4_iff_mem σ).symm

/-- The listed patterns are the identity, four powers of the rotation, and
their products with the reflection. -/
theorem dihedral4_eq_generator_words :
    dihedral4 =
      {1, p2341, p2341 ^ 2, p2341 ^ 3,
        p4321, p2341 * p4321, p2341 ^ 2 * p4321,
        p2341 ^ 3 * p4321} := by
  decide

/-- Thus the paper's eight patterns are exactly the subgroup generated by
`2341` and `4321`. -/
theorem closure_rotation_reflection_eq_dihedralSubgroup :
    Subgroup.closure ({p2341, p4321} : Set Perm4) = dihedralSubgroup := by
  apply le_antisymm
  · apply (Subgroup.closure_le dihedralSubgroup).2
    intro σ hσ
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hσ
    rcases hσ with rfl | rfl
    · exact (mem_dihedralSubgroup p2341).2 (by decide)
    · exact (mem_dihedralSubgroup p4321).2 (by decide)
  · intro σ hσ
    have hmem : σ ∈ dihedral4 :=
      (isDihedral4_iff_mem σ).mp ((mem_dihedralSubgroup σ).mp hσ)
    rw [dihedral4_eq_generator_words] at hmem
    simp only [Finset.mem_insert, Finset.mem_singleton] at hmem
    let H := Subgroup.closure ({p2341, p4321} : Set Perm4)
    have hr : p2341 ∈ H := Subgroup.subset_closure (by simp)
    have hs : p4321 ∈ H := Subgroup.subset_closure (by simp)
    rcases hmem with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · exact H.one_mem
    · exact hr
    · exact H.pow_mem hr _
    · exact H.pow_mem hr _
    · exact hs
    · exact H.mul_mem hr hs
    · exact H.mul_mem (H.pow_mem hr _) hs
    · exact H.mul_mem (H.pow_mem hr _) hs

/-- Membership in the generated subgroup is the predicate used throughout
the finite counting development. -/
theorem mem_closure_rotation_reflection_iff (σ : Perm4) :
    σ ∈ Subgroup.closure ({p2341, p4321} : Set Perm4) ↔ IsDihedral4 σ := by
  rw [closure_rotation_reflection_eq_dihedralSubgroup,
    mem_dihedralSubgroup]

end QuartetDistance.Circular
